### ISSUE TITLE
Finally test managed storage

### ISSUE THREAD

**Issue by rugk** [rugk/offline-qr-code#177]
The module we use (https://github.com/TinyWebEx/AddonSettings) does abstract all the settings of the add-on and by default tries to query the option as a managed option first. Thus, any setting we use, should theoretically be able to be overwritten by an administrator and the user should not be able to change it, afterwards.
The module [for the options page](https://github.com/TinyWebEx/AutomaticSettings) does handle the case, too.

Thus **everything is already implemented** and should™ work. However, without any testing, it is purely theory and practice can show it does not really work in one or more corner-cases (or at all :wink:).

## Docs

In addition to already linked docs for my own modules, these MD articles should explain everything that you need to know:
* https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed
* https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Native_manifests

Also it's likely good to know what options are there and how they are saved internally. Actually, you can just refer to the [default settings file](https://github.com/rugk/offline-qr-code/blob/master/src/common/modules/data/DefaultSettings.js), which should contain all options.

Don't forget to also read the [general contributing guide](https://github.com/rugk/offline-qr-code/blob/master/CONTRIBUTING.md).

## Tasks for testing

BTW, before starting, please comment here/let me know.

* [ ] Setup the management of the settings and test whether it works in general.
* [ ] Test _each_ setting.
* [ ] Test different administrator templates: lock/modify all settings, only some, only one particular etc.
* [ ] You should not be able to modify any setting in the options.
* [ ] Verify that all settings should be visibly disabled in the settings.
* [ ] Verify that each "templated" setting should take the admin's value into effect.
* [ ] Verify that the user can change all the other settings and they are applied, too.
* [ ] You, as a user, should be made aware that some settings are managed ones.
* [ ] Just try using the add-on in general (for some time) to check whether you possibly discover something else.
* [ ] Pay special attention to the `qrCodeSize` setting. As you can see, it is a JSON object. Can an admin adjust any options there, independent of the others? And can a user still modify the others?
* [ ] (optional, but recommend) Check the debugging output in the console log for errors or similar things caused by the admin template.
* [ ] (optional) Preferably, test on multiple OSes. (in case there are differences in how you e.g. provision these files)
* [ ] Document your tests (can just be in this issue as a comment), i.e. what did you test, what are the results? Which environment(s) did you use? (remember to include version numbers for OS, browser, add-on etc.) Did you had any hurdles/problems when configuring the template? Can anything else be improved? A good idea to maybe also copy this ticklist here and use it as a reference/tick it. :smiley: 

The results below list the docs, created after "post-testing"… :smile: 

## Result

* Obviously, the test result as explained above.
* Depending on the outcome, obviously bugs may have to be fixed or things may need to be changed.
  **Note:** You _do not_ have to do so. While it would be nice, obviously, this is not the task of this issue. 
* Improving/Adding docs, if necessary, may be the  most important thing of this issue. In particular:
  * [ ] Do we need some setup docs? Could it help admins to have such a thing? If so: put into GitHub wiki. (and properly link)
  * [ ] May we need to adjust the text on AMO (addons.mozilla.org) or so? (I know, at least the "WIP" label there needs to be removed.)
  * [ ] Do the docs of the [AutomaticSettings](https://github.com/TinyWebEx/AutomaticSettings) or [AddonSettings](https://github.com/TinyWebEx/AddonSettings) module need updates or even new docs? Maybe also put the guide better here?
  * [ ] possibly more that needs to be adjusted…
* Obviously, [you will be credited as a contributor](https://github.com/rugk/offline-qr-code/blob/master/CONTRIBUTORS). :smile: 

---

If you have any questions, feel free to ask. :smiley:

**Comment by EnriqueGalindo** [comment]
Hi,
I'm interested in doing this ticket if it is still available

**Comment by rugk** [comment]
Of course, thanks. Feel free to take this on.

Note that this is an issue that mostly consists of testing, so it is not assured you will get a PR at the end. However, it will likely result in at least some doc PRs, so this will then likely be a PR. :smiley:

**Comment by paulis-reece** [comment]
Can I work on this?

**Comment by rugk** [comment]
Sure, just note it's mostly a testing and doc task, as outlined before.
Thanks for your interest and if you have questions, feel free to ask. 😃

**Comment by rugk** [comment]
@ paulis-reece If you need any pointers/help or have questions, feel free to ask.
